# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntool.proto\"/\n\x0bUserMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\" \n\x0cToolResponse\x12\x10\n\x08response\x18\x01 \x01(\t27\n\x06\x41ITool\x12-\n\x0eProcessMessage\x12\x0c.UserMessage\x1a\r.ToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=14
  _globals['_USERMESSAGE']._serialized_end=61
  _globals['_TOOLRESPONSE']._serialized_start=63
  _globals['_TOOLRESPONSE']._serialized_end=95
  _globals['_AITOOL']._serialized_start=97
  _globals['_AITOOL']._serialized_end=152
# @@protoc_insertion_point(module_scope)
